// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

//! Generate a wrapper crate that bridges user code to a wasm32-wasip2 component.
//!
//! Given the resolved exports and generated WIT, this module creates a small
//! Rust crate that:
//! 1. Uses `wit_bindgen::generate!` to produce WASI bindings from the WIT
//! 2. Implements the generated `Guest` traits by delegating to the user's crate
//! 3. Compiles as a `cdylib` for the `wasm32-wasip2` target

use std::fmt::Write;
use std::path::Path;

use crate::emit::EmitConfig;
use crate::resolve::{ResolveResult, ResolvedFunction, ResolvedType};

/// Generate the complete wrapper crate directory structure.
pub fn generate_wrapper_crate(
    wrapper_dir: &Path,
    crate_root: &Path,
    wit_content: &str,
    config: &EmitConfig,
    resolved: &ResolveResult,
    crate_name: &str,
) -> miette::Result<()> {
    std::fs::create_dir_all(wrapper_dir.join("wit"))
        .map_err(|e| miette::miette!("failed to create wrapper wit dir: {e}"))?;
    std::fs::create_dir_all(wrapper_dir.join("src"))
        .map_err(|e| miette::miette!("failed to create wrapper src dir: {e}"))?;

    std::fs::write(wrapper_dir.join("wit/world.wit"), wit_content)
        .map_err(|e| miette::miette!("failed to write world.wit: {e}"))?;

    let cargo_toml = generate_cargo_toml(crate_root, crate_name);
    std::fs::write(wrapper_dir.join("Cargo.toml"), cargo_toml)
        .map_err(|e| miette::miette!("failed to write wrapper Cargo.toml: {e}"))?;

    let lib_rs = generate_lib_rs(config, resolved, crate_name);
    std::fs::write(wrapper_dir.join("src/lib.rs"), lib_rs)
        .map_err(|e| miette::miette!("failed to write wrapper src/lib.rs: {e}"))?;

    Ok(())
}

/// Generate the wrapper crate's Cargo.toml.
fn generate_cargo_toml(crate_root: &Path, crate_name: &str) -> String {
    // Use absolute path for reliability.
    let crate_path = crate_root.display();
    let component_name = format!("{crate_name}-component");

    format!(
        r#"[package]
name = "{component_name}"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
{crate_name} = {{ path = "{crate_path}" }}
wit-bindgen = "0.40"

[workspace]
"#
    )
}

/// Generate the wrapper crate's src/lib.rs.
fn generate_lib_rs(config: &EmitConfig, resolved: &ResolveResult, crate_name: &str) -> String {
    let rust_crate = crate_name.replace('-', "_");
    let ns_ident = config.namespace.replace('-', "_");
    let pkg_ident = config.package_name.replace('-', "_");
    let iface_ident = config.interface_ident();
    let world_selector = config.world_selector();

    let mut code = String::new();

    writeln!(code, "// Auto-generated by witgenstein. Do not edit.").unwrap();
    writeln!(code).unwrap();
    writeln!(code, "#[allow(warnings)]").unwrap();
    writeln!(code, "mod bindings {{").unwrap();
    writeln!(code, "    wit_bindgen::generate!({{").unwrap();
    writeln!(code, "        world: \"{world_selector}\",").unwrap();
    writeln!(code, "        path: \"wit\",").unwrap();
    writeln!(code, "    }});").unwrap();
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    let has_exports = resolved.has_exports();

    // Generate a wrapper struct for each resource (provides interior mutability).
    for imp in &resolved.impls {
        let wrapper_name = format!("{}Wrapper", imp.type_name);
        writeln!(
            code,
            "struct {wrapper_name}(std::cell::RefCell<{rust_crate}::{}>);",
            imp.type_name
        )
        .unwrap();
    }
    if !resolved.impls.is_empty() {
        writeln!(code).unwrap();
    }

    writeln!(code, "struct Component;").unwrap();
    writeln!(code).unwrap();

    // All exports (standalone functions, resources, type defs) live in a
    // single interface named after the package.
    if has_exports {
        let iface_path = format!("bindings::exports::{ns_ident}::{pkg_ident}::{iface_ident}");

        // Guest trait — associates resource types and standalone functions.
        writeln!(code, "impl {iface_path}::Guest for Component {{").unwrap();
        for imp in &resolved.impls {
            let wrapper_name = format!("{}Wrapper", imp.type_name);
            writeln!(code, "    type {} = {wrapper_name};", imp.type_name).unwrap();
        }
        for func in &resolved.functions {
            generate_fn_delegation(&mut code, func, &rust_crate, "    ");
        }
        writeln!(code, "}}").unwrap();
        writeln!(code).unwrap();

        // GuestResource trait for each resource.
        for imp in &resolved.impls {
            let wrapper_name = format!("{}Wrapper", imp.type_name);
            let guest_trait = format!("{iface_path}::Guest{}", imp.type_name);
            writeln!(code, "impl {guest_trait} for {wrapper_name} {{").unwrap();

            if let Some(ctor) = &imp.constructor {
                generate_ctor_delegation(&mut code, ctor, &rust_crate, &imp.type_name, "    ");
            }

            for method in &imp.methods {
                generate_method_delegation(&mut code, method, &rust_crate, &imp.type_name, "    ");
            }

            for static_fn in &imp.static_funcs {
                generate_static_delegation(
                    &mut code,
                    static_fn,
                    &rust_crate,
                    &imp.type_name,
                    "    ",
                );
            }

            writeln!(code, "}}").unwrap();
            writeln!(code).unwrap();
        }
    }

    writeln!(code, "bindings::export!(Component with_types_in bindings);").unwrap();

    code
}

// ---------------------------------------------------------------------------
// Delegation code generators
// ---------------------------------------------------------------------------

/// Generate a world-level function delegation.
fn generate_fn_delegation(
    code: &mut String,
    func: &ResolvedFunction,
    rust_crate: &str,
    indent: &str,
) {
    let wit_name = wit_to_rust_ident(&func.name);
    let sig = build_signature(&wit_name, &func.params, &func.return_type);
    let args = build_args(&func.params);

    writeln!(code, "{indent}{sig} {{").unwrap();
    writeln!(code, "{indent}    {rust_crate}::{}({args})", func.name).unwrap();
    writeln!(code, "{indent}}}").unwrap();
}

/// Generate a constructor delegation (wraps in RefCell).
fn generate_ctor_delegation(
    code: &mut String,
    func: &ResolvedFunction,
    rust_crate: &str,
    type_name: &str,
    indent: &str,
) {
    let params = build_param_list(&func.params);
    let args = build_args(&func.params);

    writeln!(code, "{indent}fn new({params}) -> Self {{").unwrap();
    writeln!(
        code,
        "{indent}    Self(std::cell::RefCell::new({rust_crate}::{type_name}::new({args})))"
    )
    .unwrap();
    writeln!(code, "{indent}}}").unwrap();
}

/// Generate a method delegation (borrows through RefCell).
fn generate_method_delegation(
    code: &mut String,
    func: &ResolvedFunction,
    rust_crate: &str,
    type_name: &str,
    indent: &str,
) {
    let wit_name = wit_to_rust_ident(&func.name);
    let params = build_param_list(&func.params);
    let ret = build_return_type(&func.return_type);
    let args = build_args(&func.params);

    let self_param = if params.is_empty() {
        "&self".to_string()
    } else {
        format!("&self, {params}")
    };

    let borrow = if func.is_mut_self {
        "borrow_mut"
    } else {
        "borrow"
    };

    let args_with_comma = if args.is_empty() {
        String::new()
    } else {
        format!(", {args}")
    };

    writeln!(code, "{indent}fn {wit_name}({self_param}){ret} {{").unwrap();
    writeln!(
        code,
        "{indent}    {rust_crate}::{type_name}::{}(&{}*self.0.{borrow}(){args_with_comma})",
        func.name,
        if func.is_mut_self { "mut " } else { "" },
    )
    .unwrap();
    writeln!(code, "{indent}}}").unwrap();
}

/// Generate a static function delegation.
fn generate_static_delegation(
    code: &mut String,
    func: &ResolvedFunction,
    rust_crate: &str,
    type_name: &str,
    indent: &str,
) {
    let wit_name = wit_to_rust_ident(&func.name);
    let sig = build_signature(&wit_name, &func.params, &func.return_type);
    let args = build_args(&func.params);

    writeln!(code, "{indent}{sig} {{").unwrap();
    writeln!(
        code,
        "{indent}    {rust_crate}::{type_name}::{}({args})",
        func.name
    )
    .unwrap();
    writeln!(code, "{indent}}}").unwrap();
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Build a `fn name(params) -> Ret` signature line.
fn build_signature(
    name: &str,
    params: &[(String, ResolvedType)],
    return_type: &Option<ResolvedType>,
) -> String {
    let params_str = build_param_list(params);
    let ret = build_return_type(return_type);
    format!("fn {name}({params_str}){ret}")
}

/// Build `name: Type, name2: Type2` parameter list.
fn build_param_list(params: &[(String, ResolvedType)]) -> String {
    params
        .iter()
        .map(|(name, ty)| {
            let ident = wit_to_rust_ident(name);
            let rust_ty = resolved_type_to_rust(ty);
            format!("{ident}: {rust_ty}")
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Build `arg1, arg2` argument pass-through list.
fn build_args(params: &[(String, ResolvedType)]) -> String {
    params
        .iter()
        .map(|(name, _)| wit_to_rust_ident(name))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Build ` -> Type` return clause (empty string for unit/void).
fn build_return_type(return_type: &Option<ResolvedType>) -> String {
    match return_type {
        Some(ret) if !matches!(ret, ResolvedType::Tuple(e) if e.is_empty()) => {
            format!(" -> {}", resolved_type_to_rust(ret))
        }
        _ => String::new(),
    }
}

/// Convert a Rust name to the identifier wit-bindgen would use.
///
/// WIT names are kebab-case, and wit-bindgen converts them to snake_case.
fn wit_to_rust_ident(name: &str) -> String {
    wit_common::to_kebab_case(name).replace('-', "_")
}

/// Convert a `ResolvedType` back to its Rust type string.
fn resolved_type_to_rust(ty: &ResolvedType) -> String {
    match ty {
        ResolvedType::Bool => "bool".into(),
        ResolvedType::U8 => "u8".into(),
        ResolvedType::U16 => "u16".into(),
        ResolvedType::U32 => "u32".into(),
        ResolvedType::U64 => "u64".into(),
        ResolvedType::S8 => "i8".into(),
        ResolvedType::S16 => "i16".into(),
        ResolvedType::S32 => "i32".into(),
        ResolvedType::S64 => "i64".into(),
        ResolvedType::F32 => "f32".into(),
        ResolvedType::F64 => "f64".into(),
        ResolvedType::Char => "char".into(),
        ResolvedType::WitString => "String".into(),
        ResolvedType::List(inner) => format!("Vec<{}>", resolved_type_to_rust(inner)),
        ResolvedType::Option(inner) => format!("Option<{}>", resolved_type_to_rust(inner)),
        ResolvedType::Result { ok, err } => {
            let ok_ty = ok
                .as_ref()
                .map(|t| resolved_type_to_rust(t))
                .unwrap_or_else(|| "()".into());
            let err_ty = err
                .as_ref()
                .map(|t| resolved_type_to_rust(t))
                .unwrap_or_else(|| "()".into());
            format!("Result<{ok_ty}, {err_ty}>")
        }
        ResolvedType::Tuple(elems) => {
            let parts: Vec<String> = elems.iter().map(resolved_type_to_rust).collect();
            format!("({})", parts.join(", "))
        }
        ResolvedType::Named(name) | ResolvedType::Own(name) | ResolvedType::Borrow(name) => {
            name.clone()
        }
    }
}
