[workspace]
members = [
    "crates/witgenstein-ts",
    "crates/wit-common",
    "crates/witgenstein-rs-macros",
    "crates/witgenstein-rs-macros/tests/fixtures/*",
    "samples/rust/*",
]

resolver = "3"

[workspace.dependencies]
witgenstein-ts = { path = "crates/witgenstein-ts" }
wit-common = { path = "crates/wit-common" }
witgenstein-rs-macros = { path = "crates/witgenstein-rs-macros" }